### ISSUE TITLE
Browser options not supported natively

### ISSUE THREAD

**Issue by alistair-broomhead** [alistair-broomhead/fattoush#5]
There is no interface to supply specific browser options for a test session, for chrome it is possible to supply `chromeOptions` in the `DesiredCapabilities` but this runs in into the issue cause by #4 

For some background the reason why we want this feature is that chromedriver is v.v. unstable over time unless you pass a load of explicit options, example: https://stackoverflow.com/questions/48450594/selenium-timed-out-receiving-message-from-renderer/52340526#52340526

**Comment by alistair-broomhead** [comment]
Currently the JSON config uses a format like [this example](https://github.com/alistair-broomhead/fattoush/blob/master/test/chrome_sauce_mac.json) where each browsers object is comprised of a json object which defines a browsers' DesiredCapabilities. It seem like this would also be the best place to put per-config browser options, but I'm caught between the idea of this, and having a separate `browserargs` section keyed by the browser name. 

The ideal would be to have both of these possible but I'm currently struggling to think of a sensible and understandable format for this, given the project's aim of simplifying selenium cross-browser testing.

For the use-case above separated browserargs options would be ideal, but I can see a scenario where you may wish to use different arguments on different platforms. Under this scenario we could fall back to using the following browsers config which was prevented previously by #4 
```
{
  "browser": "googlechrome",
  "chromeOptions": {
    "args": [
      "--disable-dev-shm-usage",
      "--disable-browser-side-navigation"
    ]
  }
}
```

However this seems like it is working against the point of this issue, and we now have two canonical ways of supplying browser arguments.

Another option would be to make this feature a 0.4 release and break the API. We could move the capabilities into an inner json object and add an options object, possibly implementing some sort of referencing to a shared config section to prevent copy-pasta all over the place

**Comment by alistair-broomhead** [comment]
Having considered this a while I'm coming around to the idea of a 0.4 release. Backwards compatibility could be maintained by having different schema-paths and a compatibility-layer in the parsing. The compatibility layer could raise deprecation warnings in 0.5 and be removed in 1.0. Current thoughts would be a structure like so:

```yaml
server:
  user: USERNAME
  key: KEY

browsers:
  capabilities:                 # string-keyed desired capabilities for reference
    chrome-osx:
      platform: MAC
      browser: googlechrome
      screen-resolution: 1280x1024
    chrome-nix:
      platform: LINUX
      browser: googlechrome
      screen-resolution: 1280x1024
  options:                      # string-keyed browser options for reference
    chrome:
      - disable-dev-shm-usage
      - disable-browser-side-navigation
  selection:
    - capabilities: chrome-osx  # Either key from browsers.capabilities, or object of same format
      options: chrome           # Either key from browsers.options, or object of same format
    
    - capabilities: chrome-nix
      options: chrome

```
